<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CategoryCreateRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            //
            'base_category' => 'required',
            'category_name' => 'required|min:3',
            'category_image' => 'required|file|image|max:5072'
            
        ];
    }

    public function attributes()
    {
        //return parent::attributes(); // TODO: Change the autogenerated stub
        return [
            'base_category' => "Üst Kategori",
            'category_name' => "Kategori Adı",
            'category_slug' => "Slug",
            'category_image' => "Kategori Resmi"
        ];
    }
}
